### PR TITLE
Support other providers

### PR DESCRIPTION
**Pull request by bzbetty**

### CODE REVIEW

**Comment by bzbetty** [comment]
sorry thought you'd understand.  I believe this small change was necessary to support other providers (Google/ADFS) etc through ACS using your library.  You actually hinted at it in your comment section of your blog post - http://blog.maartenballiauw.be/post/2012/08/07/ASPNET-Web-API-OAuth2-delegation-with-Windows-Azure-Access-Control-Service.aspx

**Comment by maartenba** [comment]
Ah yes :-) I'm a bit scared it may break current users, will run some tests next week first. Thanks for contributing though!

**Comment by bzbetty** [comment]
If it helps it works for me using Google, Windows ID, ADFS and Windows Azure as providers (via ACS obviously)

**Comment by bzbetty** [comment]
That said most claims for other providers aren't passed through, kind of makes sense as the origin server probably isn't contacted to get claims and no extra claims as passed when delegation is created.

**Comment by maartenba** [comment]
May want to make this a setting, have someone relying on the fact that the value is empty.

**Pull request merged**
